### ISSUE TITLE
 Some tips for improving a good code

### ISSUE THREAD

**Issue by TNtube** [GDColon/VVVVVV-Pygame#1]
Hello, 
(sorry for my english, I'm french)
I'm in front of this GitHub page following your video on Youtube. Indeed, after being impressed by the quality of the game, I wanted to take a look at your code. 
So I open this issue for the purpose of advising you. Indeed, I could not help but notice some simple detail to improve which can just greatly improve the quality of your code (being already very good).
The first remark I could make to you is that a 1,200 line file is just not possible ^^. Besides being complicated to navigate, it's anything but practical. My advice will be to at least separate the classes into separate files.

Also, another small detail (in itself, it works perfectly with, but it is not recommended) the use of `global` is anything but advisable. (more informations [here](https://stackoverflow.com/questions/19158339/why-are-global-variables-evil))
I know sometimes, it's hard to remove them, but a code whitout `global` is a better code ^^.
I hope my advice will be useful in your future as a developer, and I wish you good luck on your future projects!
(don't mind my GitHub's project, I don't have a lot of public repo, I prefer keep them private)

**Comment by GDColon** [comment]
Thanks for the suggestions! I'll be sure to look into them.
